services:
  caddy:
    build:
      context: .
      dockerfile: docker/caddy/Dockerfile
    volumes:
      - ./docker/caddy/Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - ./docker/caddy/certs:/etc/caddy/certs:ro

  api:
    build:
      target: dev
    volumes:
      - ./app/api:/app
    environment:
      FRANKENPHP_CONFIG: ""
      XDEBUG_MODE: debug
      XDEBUG_START_WITH_REQUEST: "yes"
      XDEBUG_SESSION: PHPSTORM
      XDEBUG_CLIENT_HOST: host.docker.internal
      APP_DEBUG: "true"
      APP_ENV: dev
      PHP_IDE_CONFIG: "serverName=sentinel"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    build:
      target: dev
    volumes:
      - ./app/api:/app
    environment:
      APP_DEBUG: "true"
      APP_ENV: dev
      XDEBUG_MODE: "off"

  web:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      VITE_API_URL: ${VITE_API_URL:-https://api.sentinel.localhost}
      VITE_WS_URL: ${VITE_WS_URL:-wss://api.sentinel.localhost/.well-known/mercure}
    volumes:
      - ./app/web:/app
      - web_node_modules:/app/node_modules
    stdin_open: true
    tty: true

  database:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sentinel.dev
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - database

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  pgadmin_data:
  web_node_modules:
