export { LoginPage } from './LoginPage'
export { RegisterPage } from './RegisterPage'
export { ActivatePage } from './ActivatePage'
export { HomePage } from './HomePage'
export { DashboardPage } from './DashboardPage'
